logo: NanobugXL # add logo name
title: NanobugXL
description: > # this means to ignore newlines until "baseurl:"
  I'll write something here when I can think of something cool to say...
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nanobugxl.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: backgrounda.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: 440179.jpg # your photo
author-name: NanobugXL # your name
about-author: Just another gamer, another dev and another human # about author
email: nanobugxl@gmail.com # your email
phone:  # your pnone number
website: http://nanobugxl.github.io # you website

# Social link
google_url:    # add url link
twitter_url: https://twitter.com/WestgateXL  # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url: https://fb.me/WestgateStudio # add url link

# Disqus
discus_identifier: westgatexl # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
